name: Publier le statut WhatsApp

on:
  push:
    branches:
      - main  # Changez selon votre branche par défaut

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests pywhatkit

      - name: Exécuter le script
        run: python whatsapp_status_publisher.py
